server_url: http://<HOST_LAN_IP>:9500
listen_addr: 0.0.0.0:8080
metrics_listen_addr: 0.0.0.0:9090

database:
  type: sqlite
  sqlite:
    path: /var/lib/headscale/db.sqlite

noise:
  private_key_path: /var/lib/headscale/noise_private.key

prefixes:
  v4: 100.64.0.0/10
  v6: fd7a:115c:a1e0::/48

derp:
  server:
    enabled: false
  urls:
    - https://controlplane.tailscale.com/derpmap/default
  auto_update_enabled: true
  update_frequency: 24h

dns:
  magic_dns: true
  base_domain: denfira-2.local.net
  nameservers:
    split: {}
    global:
      - 1.1.1.1
      - 8.8.8.8
  search_domains:
    - denfira-2.local.net
  extra_records:
    - name: vault.denfira-2.local.net
      type: A
      value: <TAILSCALE_SIDECAR_IP>
    - name: planka.denfira-2.local.net
      type: A
      value: <TAILSCALE_SIDECAR_IP>
    - name: cloud.denfira-2.local.net
      type: A
      value: <TAILSCALE_SIDECAR_IP>
